### ISSUE TITLE
Issue with output

### ISSUE THREAD

**Issue by smit1759** [ins1gn1a/Pwdlyser-CLI#5]
```
me@me:~$ pwdlyser -p file.txt --all

  #####  #     # #####  #      #   #  ####  ###### #####
  #    # #     # #    # #       # #  #      #      #    #
  #    # #  #  # #    # #        #    ####  #####  #    #
  #####  # # # # #    # #        #        # #      #####
  #      ##   ## #    # #        #   #    # #      #   #
  #      #     # #####  ######   #    ####  ###### #    #

  ---- Password analysis & reporting tool --- v2.6.0 ----

[!] Auto-update check not performed. Please check for a new version manually at https://www.github.com/ins1gn1a/pwdlyser

Traceback (most recent call last):
  File "/usr/local/bin/pwdlyser", line 870, in <module>
    check_character_analysis(full_list)
  File "/usr/local/bin/pwdlyser", line 512, in check_character_analysis
    mostUsed = (wordfreq[0])[1]
IndexError: list index out of range
```

Additionally, any other options output nothing.

**Comment by ins1gn1a** [comment]
Sorry - only just seen this. What input format are you using? It only accepts `username:password` or `username:hash:password`
